### PR TITLE
add config.schema.json to get a UI configuration dialog

### PR DESCRIPTION
**Pull request by lisanet**
This add a configuration dialog for the [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x#readme) plugin, so that users can easily configure the eveatmo plugin via the config web UI.

### CODE REVIEW

**Comment by skrollme** [comment]
Hello @lisanet , thank you for your contribution. I will try to check this out next weekend and merge the PR.

**Comment by skrollme** [comment]
Hello @lisanet , I'm currently testing your PR and everything works fine except one startup-error here: 

https://github.com/lisanet/homebridge-eveatmo/blob/master/device/weatherstation-device.js#L60
```
[2020-1-4 15:14:28] ReferenceError: NULL is not defined
    at WeatherstationDeviceType.<anonymous> (/usr/lib/node_modules/homebridge-eveatmo/device/weatherstation-device.js:60:14)
```

If I change the _NULL_ to _null_, everything works. Maybe a different node-version (I'm using 8.4). If you want I can change this and merge your PR.

**Comment by skrollme** [comment]
... one more thing: It would also be great if you can change the PR target branch to the _develop_-branch.

**Comment by lisanet** [comment]
ok, I've changed the PR to target your develop branch.

**Pull request merged**
